### ISSUE TITLE
[CY-3613] Codacy is giving error for mysql compatible  queries

### ISSUE THREAD

**Issue by santhosh34** [codacy/codacy-sqlint#18]
Codacy throwing error for all the below valid sql statements. 

CREATE DATABASE IF NOT EXISTS somedb;
CREATE USER IF NOT EXISTS 'somedb-db-admin' identified by 'somepassword';
GRANT CREATE,REFERENCES,INSERT,SELECT,UPDATE,DELETE,ALTER,DROP ON somedb.table1 to 'somedb-db-admin';

can you please provide some references to check proper format of above commands.

**Comment by josemiguelmelo** [comment]
Hi @santhosh34 ,

To analyse sql files, we have three tools: PMD (according to [their documentation](https://pmd.github.io/pmd-6.31.0/pmd_rules_plsql.html), it supports PLSQL), [TSQLLint](https://github.com/tsqllint/tsqllint/#tsqllint) (tool specific for TSQL) and SQLLint. This last tool, according to its documentation, uses PostgreSQL parser and still doesn't support MySQL  (https://github.com/purcell/sqlint#about).

So, I would say we currently don't have support for MySQL and that's why you're getting issues for valid MySQL statements.

**Comment by lolgab** [comment]
I'm closing this issue since it's not actionable on our side.
